name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ] 
  pull_request:
    branches: [ "main" ] 

jobs:
  build-and-test:
    name: Build, Lint, and Test
    runs-on: ubuntu-latest
    
    # Check for essential secrets before running the test job
    if: secrets.DB_PASS != '' && secrets.JWT_SECRET != ''

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Docker Buildx (for build environment)
        uses: docker/setup-buildx-action@v3
        
      # -----------------------------------------------------------
      # SECURITY FIX: Create .env.test using GitHub Secrets
      # We use environment variables for keys not present in the .env file
      # -----------------------------------------------------------
      - name: Create .env.test file from Secrets
        run: |
          echo "FLASK_ENV=dev" >> .env.test
          echo "DB_NAME=auth_db" >> .env.test
          echo "DB_PORT=3306" >> .env.test
          
          # Inject SECRETS from GitHub
          echo "DB_USER=${{ secrets.DB_USER }}" >> .env.test
          echo "DB_PASS=${{ secrets.DB_PASS }}" >> .env.test
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env.test
          
          # Internal Docker network hosts
          echo "WRITER_DB_HOST=db" >> .env.test
          echo "READER_DB_HOST=db" >> .env.test
          echo "REDIS_HOST=cache" >> .env.test
          echo "REDIS_PORT=6379" >> .env.test

      # -----------------------------------------------------------
      # EXECUTION FIX: Start services before running tests or linting
      # We need 'web', 'db', and 'cache' running before using 'docker compose run'
      # -----------------------------------------------------------
      - name: Build and Start Services for Testing
        # This command builds all images and starts the db and cache containers
        run: docker compose -f docker-compose.yml --env-file .env.test up -d --build
        
      # Step to wait for the database and app to be ready (Critical for functional tests)
      - name: Wait for Services to be Healthy
        uses: nev7n/wait_for_services@v1
        with:
          # Wait up to 120 seconds for the app port 5000 to be open
          timeout: 120
          host: localhost
          port: 5000

      - name: Lint with flake8
        # We must use the full 'docker compose' command to specify the service to run against
        run: docker compose run --rm app flake8 .

      - name: Run tests and generate coverage report
        # Assuming your docker-compose file defines a service named 'test' 
        # that executes pytest, or if you use 'app' service to execute tests.
        run: docker compose run --rm app pytest src/tests/ 
        
      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage_report.txt
          
  push-to-dockerhub:
    name: Push to Docker Hub
    needs: build-and-test
    if: success() && github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          # Note: Always use a variable for the image name for flexibility
          tags: 2000023946/auth-app:latest